### ISSUE TITLE
Feature Request: Need flexibility in the dimension.

### ISSUE THREAD

**Issue by JafferWilson** [tensorflow/playground#103]
I have seen that the program works fine when only 2D data or 2 inputs are given. But there s no option for adding more features if needed. 
I have 5 features as input. But I could not understand how I can add the 3D data or more dimension data set in the Playground. Hence, I would like to know how I can add features in the Playground.  
If there is a possibility please add this feature in the list. It will be awesomely helpful to the newbie like me in learning Tensorflow and other algorithms.

**Comment by ewilderj** [comment]
@JafferWilson I'm afraid I can't offer technical support here. Please post your problem on StackOverflow using the tensorflow.js tag - that's where the team is paying attention. https://stackoverflow.com/questions/tagged/tensorflow.js

**Comment by JafferWilson** [comment]
@ewilderj I tried on Stackoverflow but no one is there to support, Sir. I do not understand what I am suppose to do. I have posted number of questions there. I get donwvotes but no answers. I don't know whether the team is paying any attention to my requirements and understanding. Sir, please help me. I am stuck with Tensorflow playground as it is not giving a multi dimensional input feature.
