### ISSUE TITLE
Feature Request: Add the nn.ts with Tensorflow.js 

### ISSUE THREAD

**Issue by JafferWilson** [tensorflow/playground#105]
Please update your sample nn.ts with the Tensorflow.js so that we could know how the tensorflow works with the Playground.

**Comment by psychemedia** [comment]
Same issue as https://github.com/tensorflow/playground/issues/92

**Comment by JafferWilson** [comment]
I guess they are not even paying heed to what we talk. Better to close this and let us go our way then there.
