### ISSUE TITLE
Incorrect Rectified Linear Unit derivative 

### ISSUE THREAD

**Issue by Loreroth** [tensorflow/playground#19]
The derivative for the RELU activation function in nn.ts would seem to be incorrect.

It is defined as:
der: x => x < 0 ? 0 : 1

when it should be
der: x => x <= 0 ? 0 : 1

**Comment by Delaunay** [comment]
The derivative, when `x = 0`, is not defined.
Thanks to rounding error (float) `x` will never be equal to 0.
So I think this is a non-issue.

**Comment by vrv** [comment]
TensorFlow's implementation only propagates the gradient when x > 0, so it would be nice to have consistency, probably. https://github.com/tensorflow/tensorflow/blob/e39d8feebb9666a331345cd8d960f5ade4652bba/tensorflow/core/kernels/relu_op_functor.h#L54

**Comment by dsmilkov** [comment]
Fixed in 718a6c8f2f876d5450b105e269534ae58e70223d
