### ISSUE TITLE
Play with gradient boosting!

### ISSUE THREAD

**Issue by arogozhnikov** [tensorflow/playground#31]
Hey guys, 
there is now a companion demo for gradient boosting you can play with:
https://arogozhnikov.github.io/2016/07/05/gradient_boosting_playground.html

There are not as many setting as in this playground, but I think this is a nice visual explanation of how gradient boosting is trained.

Enjoy!

PS. I'll close this issue tomorrow.

**Comment by arogozhnikov** [comment]
closing issue as promised :)

**Comment by ibab** [comment]
Oh my! This is awesome.

**Comment by arogozhnikov** [comment]
> Oh my! This is awesome.

Thanks, Igor :)

**Comment by Vakuma** [comment]
@arogozhnikov This is super cool! Your blog posts and visualizations help a lot in understanding ML concepts. More posts please!  Thank you.

**Comment by nhanitvn** [comment]
Awesome, thanks @arogozhnikov
