### ISSUE TITLE
problem with build on windows 10

### ISSUE THREAD

**Issue by Arash2357** [tensorflow/playground#42]
this is the error log:

C:\Users\Arash\Desktop\AUTUMN16\Computational Intelligence\TensorFlow-Playground>npm run build

> deep-playground-prototype@2016.3.10 build C:\Users\Arash\Desktop\AUTUMN16\Computational Intelligence\TensorFlow-Playground
> npm run prep && npm run build-js && npm run build-css && npm run build-html

> deep-playground-prototype@2016.3.10 prep C:\Users\Arash\Desktop\AUTUMN16\Computational Intelligence\TensorFlow-Playground
> typings install && mkdir -p dist && cat node_modules/material-design-lite/material.min.js node_modules/d3/d3.min.js node_modules/seedrandom/seedrandom.min.js > dist/lib.js

typings WARN deprecated 9/7/2016, 5:27:44 AM: "registry:dt/d3#0.0.0+20160315011939" has been deprecated
typings ERR! message Unable to read typings for "d3". You should check the entry paths in "d3.d.ts" are up to date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/f3b564844485e265757d0494f8802e42e23dbc9d/d3/d3.d.ts"
typings ERR! caused by connect ECONNREFUSED 10.10.34.36:443

typings ERR! cwd C:\Users\Arash\Desktop\AUTUMN16\Computational Intelligence\TensorFlow-Playground
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Arash\\Desktop\\AUTUMN16\\Computational Intelligence\\TensorFlow-Playground\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v4.5.0
typings ERR! typings -v 0.7.12

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Arash\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "prep"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! deep-playground-prototype@2016.3.10 prep: `typings install && mkdir -p dist && cat node_modules/material-design-lite/material.min.js node_modules/d3/d3.min.js node_modules/seedrandom/seedrandom.min.js > dist/lib.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deep-playground-prototype@2016.3.10 prep script 'typings install && mkdir -p dist && cat node_modules/material-design-lite/material.min.js node_modules/d3/d3.min.js node_modules/seedrandom/seedrandom.min.js > dist/lib.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deep-playground-prototype package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && mkdir -p dist && cat node_modules/material-design-lite/material.min.js node_modules/d3/d3.min.js node_modules/seedrandom/seedrandom.min.js > dist/lib.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deep-playground-prototype
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls deep-playground-prototype
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Arash\Desktop\AUTUMN16\Computational Intelligence\TensorFlow-Playground\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Arash\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! deep-playground-prototype@2016.3.10 build: `npm run prep && npm run build-js && npm run build-css && npm run build-html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deep-playground-prototype@2016.3.10 build script 'npm run prep && npm run build-js && npm run build-css && npm run build-html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deep-playground-prototype package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run prep && npm run build-js && npm run build-css && npm run build-html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deep-playground-prototype
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls deep-playground-prototype
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Arash\Desktop\AUTUMN16\Computational Intelligence\TensorFlow-Playground\npm-debug.log

I'm beginner and appreciate any kind of help.

Thank you.

**Comment by andreabazerla** [comment]
Hi @Arash2357, it works.
Follow these instructions:

1. Download ZIP or git clone the project https://github.com/tensorflow/playground
2. Extract all files
3. Go with terminal in the root directory of the project
4. Type on terminal: 
4.1. `npm install`
4.2. `npm run serve`
4.3. `npm run build`
4.4. `npm run prep && npm run build-js && npm run build-css && npm run build-html`
4.5. `sudo apt install nodejs-legacy`
5. Go to 127.0.0.1:[port]/[root]/dist

**Comment by skyboys22** [comment]
Hi, i'm getting the same error :/

**Comment by skyboys22** [comment]
Solution:
- drop folder dist, -p and typing
- npm run build (you'll see that's error disapear)
- npm run serve 
- 127.0.0.1:8080

**Comment by lily0101** [comment]
hi，@skyboys22，I followed your solution , but it didn't work.

**Comment by dsmilkov** [comment]
Hi all, this should be resolved now since we are using OS-agnostic tools like `copyfiles` and `catw` for the build process. Let me know if you run into any other issues.
