### ISSUE TITLE
enhancement - allow end user to connect to a (personal) google sheet 

### ISSUE THREAD

**Issue by johndpope** [tensorflow/playground#66]
sync values to a sheet and update weights / values as the user changes the gui in realtime.

something akin to this
https://docs.google.com/spreadsheets/d/18bkheoJbmMUqdRFrviUy_TiooSjvvpDqiti7hm2EASY/edit#gid=2064454629

it may include written math formula pngs to gain visibility of what's happening under the hood.

<img width="1266" alt="screen shot 2017-06-30 at 12 34 06 pm" src="https://user-images.githubusercontent.com/289994/27745198-741ee29a-5d90-11e7-856d-2a95772e1a3e.png">

related
https://blog.algorithmia.com/google-sheets-algorithmia-machine-learning-spreadsheets/

**Comment by johndpope** [comment]
it's possible to complement spreadsheet with maths equations using this 
https://chrome.google.com/webstore/detail/equatio-math-made-digital/hjngolefdpdnooamgdldlkjgmdcmcjnc

<img width="1137" alt="screen shot 2017-07-01 at 15 48 31" src="https://user-images.githubusercontent.com/289994/27764993-0622c80c-5e75-11e7-8222-62ce80dbc9e5.png">

**Comment by j2l** [comment]
+1!
