### ISSUE TITLE
Usage of screenshots and short video recorings

### ISSUE THREAD

**Issue by Sternik00** [tensorflow/playground#81]
Hello,
Can I use screenshots and short videos of your tool?
It shows great amount of knowledge, and I've thought it can be very valuable for the readers :)

With regards

**Comment by dsmilkov** [comment]
Please feel free to make and use any screenshots/videos. All of the code is under Apache 2.0 A reference/citation will be appreciated. Thanks!

**Comment by Sternik00** [comment]
Great! Thank You :)
