### ISSUE TITLE
Nothing is working (No neurons, images etc) while serving local setup

### ISSUE THREAD

**Issue by rajendraarora16** [tensorflow/playground#93]
Recently I tried playground to setup in my local environment. However, the `play`, `adding neurons` and `images` are not showing in my local setup. I also tried pushing in github pages by using the following command:

`git subtree push --prefix dist origin gh-pages`

But still facing the same issue, nothing is working. please find the link below for pages where I have pushed:
[https://rajendraarora.github.io/nnetwork/](https://rajendraarora.github.io/nnetwork/)

HELP WILL BE APPRECIATED!

**Comment by rajendraarora16** [comment]
Looks like D3 is deprecated instead we have to look `rollup` and lot of packages have to be replaced.

**Comment by ziadloo** [comment]
I think this problem is either solved or it is specific to you. Because I just ran the code without any issues.

**Comment by rajendraarora16** [comment]
Thank you! I downloaded the latest stable version of npm and node as well changed my OS from mac to Ubuntu. It is working fine!
